server:
  port: 8085
  servlet:
    context-path: /contract
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/store?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Ljktn96381$$





